# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@ethersproject/abi-5.7.0" = {
      name = "_at_ethersproject_slash_abi";
      packageName = "@ethersproject/abi";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/abi/-/abi-5.7.0.tgz";
        sha512 = "351ktp42TiRcYB3H1OP8yajPeAQstMW/yCFokj/AthP9bLHzQFPlOrxOcwYEDkUAICmOHljvN4K39OMTMUa9RA==";
      };
    };
    "@ethersproject/abstract-provider-5.7.0" = {
      name = "_at_ethersproject_slash_abstract-provider";
      packageName = "@ethersproject/abstract-provider";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/abstract-provider/-/abstract-provider-5.7.0.tgz";
        sha512 = "R41c9UkchKCpAqStMYUpdunjo3pkEvZC3FAwZn5S5MGbXoMQOHIdHItezTETxAO5bevtMApSyEhn9+CHcDsWBw==";
      };
    };
    "@ethersproject/abstract-signer-5.7.0" = {
      name = "_at_ethersproject_slash_abstract-signer";
      packageName = "@ethersproject/abstract-signer";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/abstract-signer/-/abstract-signer-5.7.0.tgz";
        sha512 = "a16V8bq1/Cz+TGCkE2OPMTOUDLS3grCpdjoJCYNnVBbdYEMSgKrU0+B90s8b6H+ByYTBZN7a3g76jdIJi7UfKQ==";
      };
    };
    "@ethersproject/address-5.7.0" = {
      name = "_at_ethersproject_slash_address";
      packageName = "@ethersproject/address";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/address/-/address-5.7.0.tgz";
        sha512 = "9wYhYt7aghVGo758POM5nqcOMaE168Q6aRLJZwUmiqSrAungkG74gSSeKEIR7ukixesdRZGPgVqme6vmxs1fkA==";
      };
    };
    "@ethersproject/base64-5.7.0" = {
      name = "_at_ethersproject_slash_base64";
      packageName = "@ethersproject/base64";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/base64/-/base64-5.7.0.tgz";
        sha512 = "Dr8tcHt2mEbsZr/mwTPIQAf3Ai0Bks/7gTw9dSqk1mQvhW3XvRlmDJr/4n+wg1JmCl16NZue17CDh8xb/vZ0sQ==";
      };
    };
    "@ethersproject/bignumber-5.7.0" = {
      name = "_at_ethersproject_slash_bignumber";
      packageName = "@ethersproject/bignumber";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/bignumber/-/bignumber-5.7.0.tgz";
        sha512 = "n1CAdIHRWjSucQO3MC1zPSVgV/6dy/fjL9pMrPP9peL+QxEg9wOsVqwD4+818B6LUEtaXzVHQiuivzRoxPxUGw==";
      };
    };
    "@ethersproject/bytes-5.7.0" = {
      name = "_at_ethersproject_slash_bytes";
      packageName = "@ethersproject/bytes";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/bytes/-/bytes-5.7.0.tgz";
        sha512 = "nsbxwgFXWh9NyYWo+U8atvmMsSdKJprTcICAkvbBffT75qDocbuggBU0SJiVK2MuTrp0q+xvLkTnGMPK1+uA9A==";
      };
    };
    "@ethersproject/constants-5.7.0" = {
      name = "_at_ethersproject_slash_constants";
      packageName = "@ethersproject/constants";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/constants/-/constants-5.7.0.tgz";
        sha512 = "DHI+y5dBNvkpYUMiRQyxRBYBefZkJfo70VUkUAsRjcPs47muV9evftfZ0PJVCXYbAiCgght0DtcF9srFQmIgWA==";
      };
    };
    "@ethersproject/hash-5.7.0" = {
      name = "_at_ethersproject_slash_hash";
      packageName = "@ethersproject/hash";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/hash/-/hash-5.7.0.tgz";
        sha512 = "qX5WrQfnah1EFnO5zJv1v46a8HW0+E5xuBBDTwMFZLuVTx0tbU2kkx15NqdjxecrLGatQN9FGQKpb1FKdHCt+g==";
      };
    };
    "@ethersproject/keccak256-5.7.0" = {
      name = "_at_ethersproject_slash_keccak256";
      packageName = "@ethersproject/keccak256";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/keccak256/-/keccak256-5.7.0.tgz";
        sha512 = "2UcPboeL/iW+pSg6vZ6ydF8tCnv3Iu/8tUmLLzWWGzxWKFFqOBQFLo6uLUv6BDrLgCDfN28RJ/wtByx+jZ4KBg==";
      };
    };
    "@ethersproject/logger-5.7.0" = {
      name = "_at_ethersproject_slash_logger";
      packageName = "@ethersproject/logger";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/logger/-/logger-5.7.0.tgz";
        sha512 = "0odtFdXu/XHtjQXJYA3u9G0G8btm0ND5Cu8M7i5vhEcE8/HmF4Lbdqanwyv4uQTr2tx6b7fQRmgLrsnpQlmnig==";
      };
    };
    "@ethersproject/networks-5.7.0" = {
      name = "_at_ethersproject_slash_networks";
      packageName = "@ethersproject/networks";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/networks/-/networks-5.7.0.tgz";
        sha512 = "MG6oHSQHd4ebvJrleEQQ4HhVu8Ichr0RDYEfHzsVAVjHNM+w36x9wp9r+hf1JstMXtseXDtkiVoARAG6M959AA==";
      };
    };
    "@ethersproject/properties-5.7.0" = {
      name = "_at_ethersproject_slash_properties";
      packageName = "@ethersproject/properties";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/properties/-/properties-5.7.0.tgz";
        sha512 = "J87jy8suntrAkIZtecpxEPxY//szqr1mlBaYlQ0r4RCaiD2hjheqF9s1LVE8vVuJCXisjIP+JgtK/Do54ej4Sw==";
      };
    };
    "@ethersproject/rlp-5.7.0" = {
      name = "_at_ethersproject_slash_rlp";
      packageName = "@ethersproject/rlp";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/rlp/-/rlp-5.7.0.tgz";
        sha512 = "rBxzX2vK8mVF7b0Tol44t5Tb8gomOHkj5guL+HhzQ1yBh/ydjGnpw6at+X6Iw0Kp3OzzzkcKp8N9r0W4kYSs9w==";
      };
    };
    "@ethersproject/signing-key-5.7.0" = {
      name = "_at_ethersproject_slash_signing-key";
      packageName = "@ethersproject/signing-key";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/signing-key/-/signing-key-5.7.0.tgz";
        sha512 = "MZdy2nL3wO0u7gkB4nA/pEf8lu1TlFswPNmy8AiYkfKTdO6eXBJyUdmHO/ehm/htHw9K/qF8ujnTyUAD+Ry54Q==";
      };
    };
    "@ethersproject/strings-5.7.0" = {
      name = "_at_ethersproject_slash_strings";
      packageName = "@ethersproject/strings";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/strings/-/strings-5.7.0.tgz";
        sha512 = "/9nu+lj0YswRNSH0NXYqrh8775XNyEdUQAuf3f+SmOrnVewcJ5SBNAjF7lpgehKi4abvNNXyf+HX86czCdJ8Mg==";
      };
    };
    "@ethersproject/transactions-5.7.0" = {
      name = "_at_ethersproject_slash_transactions";
      packageName = "@ethersproject/transactions";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/transactions/-/transactions-5.7.0.tgz";
        sha512 = "kmcNicCp1lp8qanMTC3RIikGgoJ80ztTyvtsFvCYpSCfkjhD0jZ2LOrnbcuxuToLIUYYf+4XwD1rP+B/erDIhQ==";
      };
    };
    "@ethersproject/web-5.7.0" = {
      name = "_at_ethersproject_slash_web";
      packageName = "@ethersproject/web";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ethersproject/web/-/web-5.7.0.tgz";
        sha512 = "ApHcbbj+muRASVDSCl/tgxaH2LBkRMEYfLOLVa0COipx0+nlu0QKet7U2lEg0vdkh8XRSLf2nd1f1Uk9SrVSGA==";
      };
    };
    "@types/bn.js-5.1.1" = {
      name = "_at_types_slash_bn.js";
      packageName = "@types/bn.js";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/bn.js/-/bn.js-5.1.1.tgz";
        sha512 = "qNrYbZqMx0uJAfKnKclPh+dTwK33KfLHYqtyODwd5HnXOjnkhc4qgn3BrK6RWyGZm5+sIFE7Q7Vz6QQtJB7w7g==";
      };
    };
    "@types/node-18.7.14" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "18.7.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-18.7.14.tgz";
        sha512 = "6bbDaETVi8oyIARulOE9qF1/Qdi/23z6emrUh0fNJRUmjznqrixD4MpGDdgOFk5Xb0m2H6Xu42JGdvAxaJR/wA==";
      };
    };
    "@types/pbkdf2-3.1.0" = {
      name = "_at_types_slash_pbkdf2";
      packageName = "@types/pbkdf2";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/pbkdf2/-/pbkdf2-3.1.0.tgz";
        sha512 = "Cf63Rv7jCQ0LaL8tNXmEyqTHuIJxRdlS5vMh1mj5voN4+QFhVZnlZruezqpWYDiJ8UTzhP0VmeLXCmBk66YrMQ==";
      };
    };
    "@types/secp256k1-4.0.3" = {
      name = "_at_types_slash_secp256k1";
      packageName = "@types/secp256k1";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/secp256k1/-/secp256k1-4.0.3.tgz";
        sha512 = "Da66lEIFeIz9ltsdMZcpQvmrmmoqrfju8pm1BH8WbYjZSwUgCwXLb9C+9XYogwBITnbsSaMdVPb2ekf7TV+03w==";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha512 = "Oei9OH4tRh0YqU3GxhX79dM/mwVgvbZJaSNaRk+bshkj0S5cfHcgYakreBjrHwatXKbz+IoIdYLxrKim2MjW0Q==";
      };
    };
    "axios-0.27.2" = {
      name = "axios";
      packageName = "axios";
      version = "0.27.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/axios/-/axios-0.27.2.tgz";
        sha512 = "t+yRIyySRTp/wua5xEr+z1q60QmLq8ABsS5O9Me1AsE5dfKqgnCFzwiCZZ/cGNd1lq4/7akDWMxdhVlucjmnOQ==";
      };
    };
    "base-x-3.0.9" = {
      name = "base-x";
      packageName = "base-x";
      version = "3.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/base-x/-/base-x-3.0.9.tgz";
        sha512 = "H7JU6iBHTal1gp56aKoaa//YUxEaAOUiydvrV/pILqIHXTtqxSkATOnDA2u+jZ/61sD+L/412+7kzXRtWukhpQ==";
      };
    };
    "blakejs-1.2.1" = {
      name = "blakejs";
      packageName = "blakejs";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/blakejs/-/blakejs-1.2.1.tgz";
        sha512 = "QXUSXI3QVc/gJME0dBpXrag1kbzOqCjCX8/b54ntNyW6sjtoqxqRk3LTmXzaJoh71zMsDCjM+47jS7XiwN/+fQ==";
      };
    };
    "bn.js-4.11.6" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.11.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.11.6.tgz";
        sha512 = "XWwnNNFCuuSQ0m3r3C4LE3EiORltHd9M05pq6FOlVeiophzRbMo50Sbz1ehl8K3Z+jw9+vmgnXefY1hz8X+2wA==";
      };
    };
    "bn.js-4.12.0" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.12.0.tgz";
        sha512 = "c98Bf3tPniI+scsdk237ku1Dc3ujXQTSgyiPUDEOe7tRkhrqridvh8klBv0HCEso1OLOYcHuCv/cS6DNxKH+ZA==";
      };
    };
    "bn.js-5.2.1" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-5.2.1.tgz";
        sha512 = "eXRvHzWyYPBuB4NBy0cmYQjGitUrtqwbvlzP3G6VFnNRbsZQIxQ10PbKKHt8gZ/HW/D/747aDl+QkDqg3KQLMQ==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "brorand-1.1.0" = {
      name = "brorand";
      packageName = "brorand";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/brorand/-/brorand-1.1.0.tgz";
        sha512 = "cKV8tMCEpQs4hK/ik71d6LrPOnpkpGBR0wzxqr68g2m/LB2GxVYQroAjMJZRVM1Y4BCjCKc3vAamxSzOY2RP+w==";
      };
    };
    "browserify-aes-1.2.0" = {
      name = "browserify-aes";
      packageName = "browserify-aes";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-aes/-/browserify-aes-1.2.0.tgz";
        sha512 = "+7CHXqGuspUn/Sl5aO7Ea0xWGAtETPXNSAjHo48JfLdPWcMng33Xe4znFvQweqc/uzk5zSOI3H52CYnjCfb5hA==";
      };
    };
    "bs58-4.0.1" = {
      name = "bs58";
      packageName = "bs58";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs58/-/bs58-4.0.1.tgz";
        sha512 = "Ok3Wdf5vOIlBrgCvTq96gBkJw+JUEzdBgyaza5HLtPm7yTHkjRy8+JzNyHF7BHa0bNWOQIp3m5YF0nnFcOIKLw==";
      };
    };
    "bs58check-2.1.2" = {
      name = "bs58check";
      packageName = "bs58check";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs58check/-/bs58check-2.1.2.tgz";
        sha512 = "0TS1jicxdU09dwJMNZtVAfzPi6Q6QeN0pM1Fkzrjn+XYHvzMKPU3pHVpva+769iNVSfIYWf7LJ6WR+BuuMf8cA==";
      };
    };
    "buffer-xor-1.0.3" = {
      name = "buffer-xor";
      packageName = "buffer-xor";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-xor/-/buffer-xor-1.0.3.tgz";
        sha512 = "571s0T7nZWK6vB67HI5dyUF7wXiNcfaPPPTl6zYCNApANjIvYJTg7hlud/+cJpdAhS7dVzqMLmfhfHR3rAcOjQ==";
      };
    };
    "cipher-base-1.0.4" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.4.tgz";
        sha512 = "Kkht5ye6ZGmwv40uUDZztayT2ThLQGfnj/T71N/XzeZeo3nf8foyW7zGTsPYkEya3m5f3cAypH+qe7YOrM1U2Q==";
      };
    };
    "combined-stream-1.0.8" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz";
        sha512 = "FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==";
      };
    };
    "command-exists-1.2.9" = {
      name = "command-exists";
      packageName = "command-exists";
      version = "1.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-exists/-/command-exists-1.2.9.tgz";
        sha512 = "LTQ/SGc+s0Xc0Fu5WaKnR0YiygZkm9eKFvyS+fRsU7/ZWFF8ykFM6Pc9aCVf1+xasOOZpO3BAVgVrKvsqKHV7w==";
      };
    };
    "commander-8.3.0" = {
      name = "commander";
      packageName = "commander";
      version = "8.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-8.3.0.tgz";
        sha512 = "OkTL9umf+He2DZkUq8f8J9of7yL6RJKI24dVITBmNfZBmri9zYZQrKkuXiKhyfPSu8tUhnVBB1iKXevvnlR4Ww==";
      };
    };
    "commander-9.3.0" = {
      name = "commander";
      packageName = "commander";
      version = "9.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-9.3.0.tgz";
        sha512 = "hv95iU5uXPbK83mjrJKuZyFM/LBAoCV/XhVGkS5Je6tl7sxr6A0ITMw5WoRV46/UaJ46Nllm3Xt7IaJhXTIkzw==";
      };
    };
    "create-hash-1.2.0" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.2.0.tgz";
        sha512 = "z00bCGNHDG8mHAkP7CtT1qVu+bFQUPjYq/4Iv3C3kWjTFV10zIjfSoeqXo9Asws8gwSHDGj/hl2u4OGIjapeCg==";
      };
    };
    "create-hmac-1.1.7" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.7.tgz";
        sha512 = "MJG9liiZ+ogc4TzUwuvbER1JRdgvUFSB5+VR/g5h82fGaIRWMWddtKBHi7/sVhfjQZ6SehlyhvQYrcYkaUIpLg==";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha512 = "ZySD7Nf91aLB0RxL4KGrKHBXl7Eds1DAmEdcoVawXnLD7SDhpNgtuII2aAkg7a7QS41jxPSZ17p4VdGnMHk3MQ==";
      };
    };
    "detect-file-1.0.0" = {
      name = "detect-file";
      packageName = "detect-file";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-file/-/detect-file-1.0.0.tgz";
        sha512 = "DtCOLG98P007x7wiiOmfI0fi3eIKyWiLTGJ2MDnVi/E04lWGbf+JzrRHMm0rgIIZJGtHpKpbVgLWHrv8xXpc3Q==";
      };
    };
    "elliptic-6.5.4" = {
      name = "elliptic";
      packageName = "elliptic";
      version = "6.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/elliptic/-/elliptic-6.5.4.tgz";
        sha512 = "iLhC6ULemrljPZb+QutR5TQGB+pdW6KGD5RSegS+8sorOZT+rdQFbsQFJgvN3eRqNALqJer4oQ16YvJHlU8hzQ==";
      };
    };
    "ethereum-bloom-filters-1.0.10" = {
      name = "ethereum-bloom-filters";
      packageName = "ethereum-bloom-filters";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/ethereum-bloom-filters/-/ethereum-bloom-filters-1.0.10.tgz";
        sha512 = "rxJ5OFN3RwjQxDcFP2Z5+Q9ho4eIdEmSc2ht0fCu8Se9nbXjZ7/031uXoUYJ87KHCOdVeiUuwSnoS7hmYAGVHA==";
      };
    };
    "ethereum-cryptography-0.1.3" = {
      name = "ethereum-cryptography";
      packageName = "ethereum-cryptography";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ethereum-cryptography/-/ethereum-cryptography-0.1.3.tgz";
        sha512 = "w8/4x1SGGzc+tO97TASLja6SLd3fRIK2tLVcV2Gx4IB21hE19atll5Cq9o3d0ZmAYC/8aw0ipieTSiekAea4SQ==";
      };
    };
    "ethereumjs-util-7.1.5" = {
      name = "ethereumjs-util";
      packageName = "ethereumjs-util";
      version = "7.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ethereumjs-util/-/ethereumjs-util-7.1.5.tgz";
        sha512 = "SDl5kKrQAudFBUe5OJM9Ac6WmMyYmXX/6sTmLZ3ffG2eY6ZIGBes3pEDxNN6V72WyOw4CPD5RomKdsa8DAAwLg==";
      };
    };
    "ethjs-unit-0.1.6" = {
      name = "ethjs-unit";
      packageName = "ethjs-unit";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ethjs-unit/-/ethjs-unit-0.1.6.tgz";
        sha512 = "/Sn9Y0oKl0uqQuvgFk/zQgR7aw1g36qX/jzSQ5lSwlO0GigPymk4eGQfeNTD03w1dPOqfz8V77Cy43jH56pagw==";
      };
    };
    "evp_bytestokey-1.0.3" = {
      name = "evp_bytestokey";
      packageName = "evp_bytestokey";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/evp_bytestokey/-/evp_bytestokey-1.0.3.tgz";
        sha512 = "/f2Go4TognH/KvCISP7OUsHn85hT9nUkxxA9BEWxFn+Oj9o8ZNLm/40hdlgSLyuOimsrTKLUMEorQexp/aPQeA==";
      };
    };
    "expand-tilde-2.0.2" = {
      name = "expand-tilde";
      packageName = "expand-tilde";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-tilde/-/expand-tilde-2.0.2.tgz";
        sha512 = "A5EmesHW6rfnZ9ysHQjPdJRni0SRar0tjtG5MNtm9n5TUvsYU8oozprtRD4AqHxcZWWlVuAmQo2nWKfN9oyjTw==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "findup-sync-5.0.0" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-5.0.0.tgz";
        sha512 = "MzwXju70AuyflbgeOhzvQWAvvQdo1XL0A9bVvlXsYcFEBM87WR4OakL4OfZq+QRmr+duJubio+UtNQCPsVESzQ==";
      };
    };
    "follow-redirects-1.15.1" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.1.tgz";
        sha512 = "yLAMQs+k0b2m7cVxpS1VKJVvoz7SS9Td1zss3XRwXj+ZDH00RJgnuLx7E44wx02kQLrdM3aOOy+FpzS7+8OizA==";
      };
    };
    "form-data-4.0.0" = {
      name = "form-data";
      packageName = "form-data";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-4.0.0.tgz";
        sha512 = "ETEklSGi5t0QMZuiXoA/Q6vcnxcLQP5vdugSpuAyi6SVGi2clPPp+xgEhuMaHC+zGgn31Kd235W35f7Hykkaww==";
      };
    };
    "fs-extra-10.1.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "10.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-10.1.0.tgz";
        sha512 = "oRXApq54ETRj4eMiFzGnHWGy+zo5raudjuxN0b8H7s/RU2oW0Wvsx9O0ACRN/kRq9E8Vu/ReskGB5o3ji+FzHQ==";
      };
    };
    "global-modules-1.0.0" = {
      name = "global-modules";
      packageName = "global-modules";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-modules/-/global-modules-1.0.0.tgz";
        sha512 = "sKzpEkf11GpOFuw0Zzjzmt4B4UZwjOcG757PPvrfhxcLFbq0wpsgpOqxpxtxFiCG4DtG93M6XRVbF2oGdev7bg==";
      };
    };
    "global-prefix-1.0.2" = {
      name = "global-prefix";
      packageName = "global-prefix";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-prefix/-/global-prefix-1.0.2.tgz";
        sha512 = "5lsx1NUDHtSjfg0eHlmYvZKv8/nVqX4ckFbM+FrGcQ+04KWcWFo9P5MxPZYSzUvyzmdTbI7Eix8Q4IbELDqzKg==";
      };
    };
    "graceful-fs-4.2.10" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.10.tgz";
        sha512 = "9ByhssR2fPVsNZj478qUUbKfmL0+t5BDVyjShtyZZLiK7ZDAArFFfopyOTj0M05wE2tJPisA4iTnnXl2YoPvOA==";
      };
    };
    "hash-base-3.1.0" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-3.1.0.tgz";
        sha512 = "1nmYp/rhMDiE7AYkDw+lLwlAzz0AntGIe51F3RfFfEqyQ3feY2eI/NcwC6umIQVOASPMsWJLJScWKSSvzL9IVA==";
      };
    };
    "hash.js-1.1.7" = {
      name = "hash.js";
      packageName = "hash.js";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash.js/-/hash.js-1.1.7.tgz";
        sha512 = "taOaskGt4z4SOANNseOviYDvjEJinIkRgmp7LbKP2YTTmVxWBl87s/uzK9r+44BclBSp2X7K1hqeNfz9JbBeXA==";
      };
    };
    "hmac-drbg-1.0.1" = {
      name = "hmac-drbg";
      packageName = "hmac-drbg";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hmac-drbg/-/hmac-drbg-1.0.1.tgz";
        sha512 = "Tti3gMqLdZfhOQY1Mzf/AanLiqh1WTiJgEj26ZuYQ9fbkLomzGchCws4FyrSd4VkpBfiNhaE1On+lOz894jvXg==";
      };
    };
    "homedir-polyfill-1.0.3" = {
      name = "homedir-polyfill";
      packageName = "homedir-polyfill";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/homedir-polyfill/-/homedir-polyfill-1.0.3.tgz";
        sha512 = "eSmmWE5bZTK2Nou4g0AI3zZ9rswp7GRKoKXS1BLUkvPviOqs4YTN1djQIqrXy9k5gEtdLPy86JjRwsNM9tnDcA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-hex-prefixed-1.0.0" = {
      name = "is-hex-prefixed";
      packageName = "is-hex-prefixed";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-hex-prefixed/-/is-hex-prefixed-1.0.0.tgz";
        sha512 = "WvtOiug1VFrE9v1Cydwm+FnXd3+w9GaeVUss5W4v/SLy3UW00vP+6iNF2SdnfiBoLy4bTqVdkftNGTUeOFVsbA==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-windows-1.0.2" = {
      name = "is-windows";
      packageName = "is-windows";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-windows/-/is-windows-1.0.2.tgz";
        sha512 = "eXK1UInq2bPmjyX6e3VHIzMLobc4J94i4AWn+Hpq3OU5KkrRC96OAcR3PRJ/pGu6m8TRnBHP9dkXQVsT/COVIA==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "js-sha3-0.8.0" = {
      name = "js-sha3";
      packageName = "js-sha3";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-sha3/-/js-sha3-0.8.0.tgz";
        sha512 = "gF1cRrHhIzNfToc802P800N8PpXS+evLLXfsVpowqmAFR9uwbi89WvXg2QspOmXL8QL86J4T1EpFu+yUkwJY3Q==";
      };
    };
    "jsel-1.1.6" = {
      name = "jsel";
      packageName = "jsel";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsel/-/jsel-1.1.6.tgz";
        sha512 = "7E6r8kVzjmKhwXR/82Z+43edfOJGRvLvx6cJZ+SS2MGAPPtYZGnaIsFHpQMA1IbIPA9twDProkob4IIAJ0ZqSw==";
      };
    };
    "jsonfile-6.1.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.1.0.tgz";
        sha512 = "5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==";
      };
    };
    "keccak-3.0.2" = {
      name = "keccak";
      packageName = "keccak";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/keccak/-/keccak-3.0.2.tgz";
        sha512 = "PyKKjkH53wDMLGrvmRGSNWgmSxZOUqbnXwKL9tmgbFYA1iAYqW21kfR7mZXV0MlESiefxQQE9X9fTa3X+2MPDQ==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "md5.js-1.3.5" = {
      name = "md5.js";
      packageName = "md5.js";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5.js/-/md5.js-1.3.5.tgz";
        sha512 = "xitP+WxNPcTTOgnTJcrhM0xvdPepipPSf3I8EIpGKeFLjt3PlJLIDG3u8EX53ZIubkb+5U2+3rELYpEhHhzdkg==";
      };
    };
    "memorystream-0.3.1" = {
      name = "memorystream";
      packageName = "memorystream";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/memorystream/-/memorystream-0.3.1.tgz";
        sha512 = "S3UwM3yj5mtUSEfP41UZmt/0SCoVYUcU1rkXv+BQ5Ig8ndL4sPoJNBUJERafdPb5jjHJGuMgytgKvKIf58XNBw==";
      };
    };
    "micromatch-4.0.5" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.5.tgz";
        sha512 = "DMy+ERcEW2q8Z2Po+WNXuw3c5YaUSFjAO5GsJqfEl7UjvtIuFKO6ZrKvcItdy98dwFI2N1tg3zNIdKaQT+aNdA==";
      };
    };
    "mime-db-1.52.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz";
        sha512 = "sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==";
      };
    };
    "mime-types-2.1.35" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz";
        sha512 = "ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==";
      };
    };
    "minimalistic-assert-1.0.1" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz";
        sha512 = "UtJcAD4yEaGtjPezWuO9wC4nwUnVH/8/Im3yEHQP4b67cXlD/Qr9hdITCU1xDbSEXg2XKNaP8jsReV7vQd00/A==";
      };
    };
    "minimalistic-crypto-utils-1.0.1" = {
      name = "minimalistic-crypto-utils";
      packageName = "minimalistic-crypto-utils";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-crypto-utils/-/minimalistic-crypto-utils-1.0.1.tgz";
        sha512 = "JIYlbt6g8i5jKfJ3xz7rF0LXmv2TkDxBLUkiBeZ7bAx4GnnNMr8xFpGnOxn6GhTEHx3SjRrZEoU+j04prX1ktg==";
      };
    };
    "node-addon-api-2.0.2" = {
      name = "node-addon-api";
      packageName = "node-addon-api";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-addon-api/-/node-addon-api-2.0.2.tgz";
        sha512 = "Ntyt4AIXyaLIuMHF6IOoTakB3K+RWxwtsHNRxllEoA6vPwP9o4866g6YWDLUdnucilZhmkxiHwHr11gAENw+QA==";
      };
    };
    "node-gyp-build-4.5.0" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.5.0.tgz";
        sha512 = "2iGbaQBV+ITgCz76ZEjmhUKAKVf7xfY1sRl4UiKQspfZMH2h06SyhNsnSVy50cwkFQDGLyif6m/6uFXHkOZ6rg==";
      };
    };
    "number-to-bn-1.7.0" = {
      name = "number-to-bn";
      packageName = "number-to-bn";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-to-bn/-/number-to-bn-1.7.0.tgz";
        sha512 = "wsJ9gfSz1/s4ZsJN01lyonwuxA1tml6X1yBDnfpMglypcBRFZZkus26EdPSlqS5GJfYddVZa22p3VNb3z5m5Ig==";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha512 = "D2FR03Vir7FIu45XBY20mTb+/ZSWB00sjU9jdQXt83gDrI4Ztz5Fs7/yy74g2N5SVQY4xY1qDr4rNddwYRVX0g==";
      };
    };
    "parse-passwd-1.0.0" = {
      name = "parse-passwd";
      packageName = "parse-passwd";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-passwd/-/parse-passwd-1.0.0.tgz";
        sha512 = "1Y1A//QUXEZK7YKz+rD9WydcE1+EuPr6ZBgKecAB8tmoW6UFv0NREVJe1p+jRxtThkcbbKkfwIbWJe/IeE6m2Q==";
      };
    };
    "pbkdf2-3.1.2" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.1.2.tgz";
        sha512 = "iuh7L6jA7JEGu2WxDwtQP1ddOpaJNC4KlDEFfdQajSGgGPNi4OyDc2R7QnbY2bR9QjBVGwgvTdNJZoE7RaxUMA==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "resolve-dir-1.0.1" = {
      name = "resolve-dir";
      packageName = "resolve-dir";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-dir/-/resolve-dir-1.0.1.tgz";
        sha512 = "R7uiTjECzvOsWSfdM0QKFNBVFcK27aHOUwdvK53BcW8zqnGdYp0Fbj82cy54+2A4P2tFM22J5kRfe1R+lM/1yg==";
      };
    };
    "ripemd160-2.0.2" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-2.0.2.tgz";
        sha512 = "ii4iagi25WusVoiC4B4lq7pbXfAp3D9v5CwfkY33vffw2+pkDjY1D8GaN7spsxvCSx8dkPqOZCEZyfxcmJG2IA==";
      };
    };
    "rlp-2.2.7" = {
      name = "rlp";
      packageName = "rlp";
      version = "2.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/rlp/-/rlp-2.2.7.tgz";
        sha512 = "d5gdPmgQ0Z+AklL2NVXr/IoSjNZFfTVvQWzL/AM2AOcSzYP2xjlb0AC8YyCLc41MSNf6P6QVtjgPdmVtzb+4lQ==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "scrypt-js-3.0.1" = {
      name = "scrypt-js";
      packageName = "scrypt-js";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/scrypt-js/-/scrypt-js-3.0.1.tgz";
        sha512 = "cdwTTnqPu0Hyvf5in5asVdZocVDTNRmR7XEcJuIzMjJeSHybHl7vpB66AzwTaIg6CLSbtjcxc8fqcySfnTkccA==";
      };
    };
    "secp256k1-4.0.3" = {
      name = "secp256k1";
      packageName = "secp256k1";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/secp256k1/-/secp256k1-4.0.3.tgz";
        sha512 = "NLZVf+ROMxwtEj3Xa562qgv2BK5e2WNmXPiOdVIPLgs6lyTzMvBq0aWTYMI5XCP9jZMVKOcqZLw/Wc4vDkuxhA==";
      };
    };
    "semver-5.7.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz";
        sha512 = "sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==";
      };
    };
    "semver-7.3.7" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.7.tgz";
        sha512 = "QlYTucUYOews+WeEujDoEGziz4K6c47V/Bd+LjSSYcA94p+DmINdf7ncaUinThfvZyu13lN9OY1XDxt8C0Tw0g==";
      };
    };
    "setimmediate-1.0.5" = {
      name = "setimmediate";
      packageName = "setimmediate";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/setimmediate/-/setimmediate-1.0.5.tgz";
        sha512 = "MATJdZp8sLqDl/68LfQmbP8zKPLQNV6BIZoIgrscFDQ+RsvK/BxeDQOgyxKKoh0y/8h3BqVFnCqQ/gd+reiIXA==";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 = "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "solc-0.8.16" = {
      name = "solc";
      packageName = "solc";
      version = "0.8.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/solc/-/solc-0.8.16.tgz";
        sha512 = "6oZg7FAhIouj2zYLvoR3Q4fMP/+BGPR7sY7GcrEXKIp+DRd8RmpDEFO1LUBKpClUiaYguNgmthTFmnPl4MeiMQ==";
      };
    };
    "solc-typed-ast-10.1.4" = {
      name = "solc-typed-ast";
      packageName = "solc-typed-ast";
      version = "10.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/solc-typed-ast/-/solc-typed-ast-10.1.4.tgz";
        sha512 = "xz3DKfTMURzRY9YYtOYsHafHNBM5I0TOoGFkrQ2uoOT5IAxnbpbTTD1W1ySDCqWDCAZuGu9Wq1H/wvm3R5oHCw==";
      };
    };
    "src-location-1.1.0" = {
      name = "src-location";
      packageName = "src-location";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/src-location/-/src-location-1.1.0.tgz";
        sha512 = "idBVZgLZGzB3B2Et317AFDQto7yRgp1tOuFd+VKIH2dw1jO1b6p07zNjtQoVhkW+CY6oGTp9Y5UIfbJoZRsoFQ==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-hex-prefix-1.0.0" = {
      name = "strip-hex-prefix";
      packageName = "strip-hex-prefix";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-hex-prefix/-/strip-hex-prefix-1.0.0.tgz";
        sha512 = "q8d4ue7JGEiVcypji1bALTos+0pWtyGlivAWyPuTkHzuTCJqrK9sWxYQZUq6Nq3cuyv3bm734IhHvHtGGURU6A==";
      };
    };
    "tmp-0.0.33" = {
      name = "tmp";
      packageName = "tmp";
      version = "0.0.33";
      src = fetchurl {
        url = "https://registry.npmjs.org/tmp/-/tmp-0.0.33.tgz";
        sha512 = "jRCJlojKnZ3addtTOjdIqoRuPEKBvNXcGYqzO6zWZX8KfKEpnGY5jfggJQ3EjKuu8D4bJRr0y+cYJFmYbImXGw==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "universalify-2.0.0" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.0.tgz";
        sha512 = "hAZsKq7Yy11Zu1DE0OzWjw7nnLZmJZYTDZZyEFHZdUhV8FkH5MCfoU1XMaxXovpyW5nq5scPqq0ZDP9Zyl04oQ==";
      };
    };
    "utf8-3.0.0" = {
      name = "utf8";
      packageName = "utf8";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf8/-/utf8-3.0.0.tgz";
        sha512 = "E8VjFIQ/TyQgp+TZfS6l8yp/xWppSAHzidGiRrqe4bK4XP9pTRyKFgGJpO3SN7zdX4DeomTrwaseCHovfpFcqQ==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "web3-eth-abi-1.7.5" = {
      name = "web3-eth-abi";
      packageName = "web3-eth-abi";
      version = "1.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/web3-eth-abi/-/web3-eth-abi-1.7.5.tgz";
        sha512 = "qWHvF7sayxql9BD1yqK9sZRLBQ66eJzGeaU53Y1PRq2iFPrhY6NUWxQ3c3ps0rg+dyObvRbloviWpKXcS4RE/A==";
      };
    };
    "web3-utils-1.7.5" = {
      name = "web3-utils";
      packageName = "web3-utils";
      version = "1.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/web3-utils/-/web3-utils-1.7.5.tgz";
        sha512 = "9AqNOziQky4wNQadEwEfHiBdOZqopIHzQQVzmvvv6fJwDSMhP+khqmAZC7YTiGjs0MboyZ8tWNivqSO1699XQw==";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
  args = {
    name = "soliditypreprocessor";
    packageName = "soliditypreprocessor";
    version = "1.0.0";
    src = ../../deps/SolidityPreprocessor;
    dependencies = [
      sources."@ethersproject/abi-5.7.0"
      sources."@ethersproject/abstract-provider-5.7.0"
      sources."@ethersproject/abstract-signer-5.7.0"
      sources."@ethersproject/address-5.7.0"
      sources."@ethersproject/base64-5.7.0"
      sources."@ethersproject/bignumber-5.7.0"
      sources."@ethersproject/bytes-5.7.0"
      sources."@ethersproject/constants-5.7.0"
      sources."@ethersproject/hash-5.7.0"
      sources."@ethersproject/keccak256-5.7.0"
      sources."@ethersproject/logger-5.7.0"
      sources."@ethersproject/networks-5.7.0"
      sources."@ethersproject/properties-5.7.0"
      sources."@ethersproject/rlp-5.7.0"
      sources."@ethersproject/signing-key-5.7.0"
      sources."@ethersproject/strings-5.7.0"
      sources."@ethersproject/transactions-5.7.0"
      sources."@ethersproject/web-5.7.0"
      sources."@types/bn.js-5.1.1"
      sources."@types/node-18.7.14"
      sources."@types/pbkdf2-3.1.0"
      sources."@types/secp256k1-4.0.3"
      sources."asynckit-0.4.0"
      sources."axios-0.27.2"
      sources."base-x-3.0.9"
      sources."blakejs-1.2.1"
      sources."bn.js-5.2.1"
      sources."braces-3.0.2"
      sources."brorand-1.1.0"
      sources."browserify-aes-1.2.0"
      sources."bs58-4.0.1"
      sources."bs58check-2.1.2"
      sources."buffer-xor-1.0.3"
      sources."cipher-base-1.0.4"
      sources."combined-stream-1.0.8"
      sources."command-exists-1.2.9"
      sources."commander-9.3.0"
      sources."create-hash-1.2.0"
      sources."create-hmac-1.1.7"
      sources."delayed-stream-1.0.0"
      sources."detect-file-1.0.0"
      (sources."elliptic-6.5.4" // {
        dependencies = [
          sources."bn.js-4.12.0"
        ];
      })
      sources."ethereum-bloom-filters-1.0.10"
      sources."ethereum-cryptography-0.1.3"
      sources."ethereumjs-util-7.1.5"
      (sources."ethjs-unit-0.1.6" // {
        dependencies = [
          sources."bn.js-4.11.6"
        ];
      })
      sources."evp_bytestokey-1.0.3"
      sources."expand-tilde-2.0.2"
      sources."fill-range-7.0.1"
      sources."findup-sync-5.0.0"
      sources."follow-redirects-1.15.1"
      sources."form-data-4.0.0"
      sources."fs-extra-10.1.0"
      sources."global-modules-1.0.0"
      sources."global-prefix-1.0.2"
      sources."graceful-fs-4.2.10"
      sources."hash-base-3.1.0"
      sources."hash.js-1.1.7"
      sources."hmac-drbg-1.0.1"
      sources."homedir-polyfill-1.0.3"
      sources."inherits-2.0.4"
      sources."ini-1.3.8"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-hex-prefixed-1.0.0"
      sources."is-number-7.0.0"
      sources."is-windows-1.0.2"
      sources."isexe-2.0.0"
      sources."js-sha3-0.8.0"
      sources."jsel-1.1.6"
      sources."jsonfile-6.1.0"
      sources."keccak-3.0.2"
      sources."lru-cache-6.0.0"
      sources."md5.js-1.3.5"
      sources."memorystream-0.3.1"
      sources."micromatch-4.0.5"
      sources."mime-db-1.52.0"
      sources."mime-types-2.1.35"
      sources."minimalistic-assert-1.0.1"
      sources."minimalistic-crypto-utils-1.0.1"
      sources."node-addon-api-2.0.2"
      sources."node-gyp-build-4.5.0"
      (sources."number-to-bn-1.7.0" // {
        dependencies = [
          sources."bn.js-4.11.6"
        ];
      })
      sources."os-tmpdir-1.0.2"
      sources."parse-passwd-1.0.0"
      sources."pbkdf2-3.1.2"
      sources."picomatch-2.3.1"
      sources."randombytes-2.1.0"
      sources."readable-stream-3.6.0"
      sources."resolve-dir-1.0.1"
      sources."ripemd160-2.0.2"
      sources."rlp-2.2.7"
      sources."safe-buffer-5.2.1"
      sources."scrypt-js-3.0.1"
      sources."secp256k1-4.0.3"
      sources."semver-7.3.7"
      sources."setimmediate-1.0.5"
      sources."sha.js-2.4.11"
      (sources."solc-0.8.16" // {
        dependencies = [
          sources."commander-8.3.0"
          sources."semver-5.7.1"
        ];
      })
      sources."solc-typed-ast-10.1.4"
      sources."src-location-1.1.0"
      sources."string_decoder-1.3.0"
      sources."strip-hex-prefix-1.0.0"
      sources."tmp-0.0.33"
      sources."to-regex-range-5.0.1"
      sources."universalify-2.0.0"
      sources."utf8-3.0.0"
      sources."util-deprecate-1.0.2"
      sources."web3-eth-abi-1.7.5"
      sources."web3-utils-1.7.5"
      sources."which-1.3.1"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Preprocesses and summarizes a solidity file";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
