name: CI
on:
  push:
    branches: [ v1 ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2.4.0
        with: 
          submodules: recursive
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://releases.nixos.org/nix/nix-2.9.2/install
      - uses: cachix/cachix-action@v10
        with:
          name: veridise-public
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build libVanguard component
        run: |
          nix build --print-build-logs .#libVanguard
          echo "Done."
      - name: Build preprocessor components
        run: |
          nix build .#rust-preprocessor '.?submodules=1#solidity-preprocessor'
      # - name: Test IR Validator
      #   run: |
      #     python3 run.py --src_path test/PuppetPool.sol  --detector irValidator
      #     echo "Done."
